name: "JVM & JS Tests"

on:
  pull_request:
    types: [ opened, synchronize ] # Don't rerun on `edited` to save time
  push:
    branches: # Runs on develop to have the coverage diff on every PR
      - 'develop'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  gradle-run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Test JVM
        run: ./gradlew jvmTest

      - name: Test JS
        run: ./gradlew jsTest

      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
